runtime: java17
env: standard
service: chatbot-hook
# remember to use an instance class compatible with your scaling type
instance_class: B1
handlers:
  - url: .*
    script: auto
basic_scaling:
  max_instances: 3
  idle_timeout: 10m
service_account: workload@hack-team-thewarroom1.iam.gserviceaccount.com